/* This file is autogenerated, do not edit*/
#include "moc_debugger.cpp"
#include "moc_debugmessage.cpp"
#include "moc_game.cpp"
#include "moc_gameover.cpp"
#include "moc_highscore.cpp"
#include "moc_welcome.cpp"
